# Generated by Django 4.0.1 on 2022-02-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('Job_Title', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Phone', models.IntegerField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
