# Generated by Django 4.0.1 on 2022-03-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0003_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
