# Generated by Django 4.0.2 on 2022-02-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0003_person_others_alter_person_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Others',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
