# Generated by Django 4.0.2 on 2022-02-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0004_alter_person_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Others',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
