# Generated by Django 4.0.1 on 2022-03-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0004_alter_person_website_alter_profiles_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
