# Generated by Django 4.0.1 on 2022-03-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0007_remove_person_others_alter_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Website',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
