# Generated by Django 4.0.1 on 2022-03-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0008_person_mobile_person_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
